database queries
Okimmi/stackNinjas-frontend pull request #10
Opened 2023-12-24 17:56 UTC by ValentynaJasochka

I haven't changed styles because there is no information about the home page design. Please don't match them. I will correct them later

2023-12-24 18:20 UTC, sili41995 approved these changes

2023-12-25 08:39 UTC, Okimmi approved these changes

2023-12-25 08:43 UTC, Okimmi requested changes

2023-12-25 08:43 UTC, Okimmi commented on src/pages/HomePage/HomePage.jsx
> +import { MonthStatesTable } from 'components/MonthStatesTable/MonthStatesTable.jsx';
Є імпорт компоненту, але він не використовується, через це буде провал деплою.

2023-12-25 13:53 UTC, Okimmi approved these changes

2023-12-25 13:54 UTC, closed without merging