Fix data daily normal
Okimmi/stackNinjas-frontend pull request #20
Opened 2023-12-26 20:57 UTC by SSSerg05

2023-12-26 21:32 UTC, Okimmi requested changes

2023-12-26 21:32 UTC, Okimmi commented on src/redux/auth/operations.js
> +      await axios.get('/api/auth/current');
await axios.get('/api/auth/current'); не треба

2023-12-26 21:32 UTC, Okimmi commented on src/redux/auth/operations.js
>        return res.data;
return res.data.dailyWaterRequirement;

2023-12-26 21:32 UTC, Okimmi commented on src/redux/auth/slice.js
> +      state.user = action.payload;
state.user.dailyWaterRequirement = action.payload;

2023-12-26 21:32 UTC, Okimmi commented on src/redux/auth/slice.js
> +      state.isLoggedIn = true;
Не треба

2023-12-26 21:37 UTC, SSSerg05 commented on src/redux/auth/operations.js
> +      await axios.get('/api/auth/current');
+++

2023-12-26 21:38 UTC, SSSerg05 commented on src/redux/auth/operations.js
>        return res.data;
+++

2023-12-27 05:56 UTC, SSSerg05 commented on src/redux/auth/slice.js
> +      state.user = action.payload;
+++

2023-12-27 05:57 UTC, SSSerg05 commented on src/redux/auth/slice.js
> +      state.isLoggedIn = true;
не зрозумів що саме не требв

2023-12-27 19:40 UTC, Okimmi approved these changes

2023-12-27 19:40 UTC, Okimmi commented on src/redux/auth/slice.js
> +      state.isLoggedIn = true;
state.isLoggedIn = true;

2023-12-27 19:40 UTC, merged